#!/usr/bin/env bash
# =============================================================================
#  3reco – one-command production deploy
#
#  Usage:
#    RESEND_API_KEY=... AUTH_FROM_EMAIL=... ./deploy.sh <domain>
#
#  Example:
#    ./deploy.sh yourdomain.com
#
#  What it does:
#    1. Derives all service URLs from the domain you provide
 #    2. Generates secure INSTANCE_SECRET and BETTER_AUTH_SECRET values if they are not already in .env
#    3. Writes (or updates) .env
#    4. Runs: docker compose up -d --build
#
#  Prerequisites:
#    - Docker >= 24 with Compose v2
#    - DNS A records for all five subdomains pointing at this server:
#        app.<domain>
#        docs.<domain>
#        convex.<domain>
#        convex-site.<domain>
#        convex-dashboard.<domain>
# =============================================================================

set -euo pipefail

DOMAIN="${1:-}"
BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET:-}"
RESEND_API_KEY="${RESEND_API_KEY:-}"
AUTH_FROM_EMAIL="${AUTH_FROM_EMAIL:-}"

if [[ -z "$DOMAIN" ]]; then
  echo "Usage: $0 <domain>"
  echo "  e.g. RESEND_API_KEY=re_xxx AUTH_FROM_EMAIL=noreply@yourdomain.com $0 yourdomain.com"
  exit 1
fi

ENV_FILE=".env"

# ── Generate or preserve INSTANCE_SECRET ──────────────────────────────────────
# If .env already contains a non-empty INSTANCE_SECRET, keep it so existing
# Convex data remains accessible after re-deploys.
EXISTING_SECRET=""
if [[ -f "$ENV_FILE" ]]; then
  EXISTING_SECRET=$(grep -E '^INSTANCE_SECRET=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
fi

if [[ -n "$EXISTING_SECRET" ]]; then
  INSTANCE_SECRET="$EXISTING_SECRET"
  echo "ℹ️  Reusing existing INSTANCE_SECRET from $ENV_FILE"
else
  INSTANCE_SECRET=$(openssl rand -hex 32)
  echo "✅ Generated new INSTANCE_SECRET"
fi

EXISTING_BETTER_AUTH_SECRET=""
EXISTING_RESEND_API_KEY=""
EXISTING_AUTH_FROM_EMAIL=""

if [[ -f "$ENV_FILE" ]]; then
  EXISTING_BETTER_AUTH_SECRET=$(grep -E '^BETTER_AUTH_SECRET=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
  EXISTING_RESEND_API_KEY=$(grep -E '^RESEND_API_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
  EXISTING_AUTH_FROM_EMAIL=$(grep -E '^AUTH_FROM_EMAIL=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
fi

if [[ -z "$BETTER_AUTH_SECRET" && -n "$EXISTING_BETTER_AUTH_SECRET" ]]; then
  BETTER_AUTH_SECRET="$EXISTING_BETTER_AUTH_SECRET"
  echo "ℹ️  Reusing existing BETTER_AUTH_SECRET from $ENV_FILE"
fi

if [[ -z "$BETTER_AUTH_SECRET" ]]; then
  BETTER_AUTH_SECRET=$(openssl rand -hex 32)
  echo "✅ Generated new BETTER_AUTH_SECRET"
fi

if [[ -z "$RESEND_API_KEY" && -n "$EXISTING_RESEND_API_KEY" ]]; then
  RESEND_API_KEY="$EXISTING_RESEND_API_KEY"
  echo "ℹ️  Reusing existing RESEND_API_KEY from $ENV_FILE"
fi

if [[ -z "$AUTH_FROM_EMAIL" && -n "$EXISTING_AUTH_FROM_EMAIL" ]]; then
  AUTH_FROM_EMAIL="$EXISTING_AUTH_FROM_EMAIL"
  echo "ℹ️  Reusing existing AUTH_FROM_EMAIL from $ENV_FILE"
fi

SITE_URL="https://app.$DOMAIN"

if [[ -z "$RESEND_API_KEY" ]]; then
  echo "⚠️  RESEND_API_KEY is not set. Password reset and verification emails will fail until you add it."
else
  echo "✅ Using RESEND_API_KEY from environment/.env"
fi

if [[ -z "$AUTH_FROM_EMAIL" ]]; then
  echo "⚠️  AUTH_FROM_EMAIL is not set. Better Auth emails will fail until you add it."
else
  echo "✅ Using AUTH_FROM_EMAIL: $AUTH_FROM_EMAIL"
fi

# ── Write .env ─────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — do not commit this file
DOMAIN=$DOMAIN

INSTANCE_NAME=3reco-production
INSTANCE_SECRET=$INSTANCE_SECRET

CONVEX_CLOUD_ORIGIN=https://convex.$DOMAIN
CONVEX_SITE_ORIGIN=https://convex-site.$DOMAIN

VITE_CONVEX_URL=https://convex.$DOMAIN
VITE_CONVEX_SITE_URL=https://convex-site.$DOMAIN

BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
SITE_URL=$SITE_URL
RESEND_API_KEY=$RESEND_API_KEY
AUTH_FROM_EMAIL=$AUTH_FROM_EMAIL
EOF

echo "✅ Written $ENV_FILE for domain: $DOMAIN"

# ── Build Docker images ─────────────────────────────────────────────────────
echo ""
echo "🔧 Building Docker images..."
docker compose build --no-cache

# ── Deploy ─────────────────────────────────────────────────────────────────────
echo ""
echo "🚀 Starting stack..."
docker compose up -d

echo ""
echo "✅ Stack is up. Services:"
echo "   https://app.$DOMAIN"
echo "   https://docs.$DOMAIN"
echo "   https://convex.$DOMAIN"
echo "   https://convex-site.$DOMAIN"
echo "   https://convex-dashboard.$DOMAIN"
echo ""
echo "⚠️  First deploy? Generate the Convex admin key:"
echo "   docker compose exec convex-backend ./generate_admin_key.sh"
echo ""
echo "   Then deploy Convex functions:"
echo "   cd 3reco && CONVEX_SELF_HOSTED_URL=https://convex.$DOMAIN \\"
echo "     CONVEX_SELF_HOSTED_ADMIN_KEY=<key> bunx convex deploy"
