#!/usr/bin/env bash
# =============================================================================
#  3reco – one-command production deploy
#
#  Usage:
#    ./deploy.sh <domain>
#
#  Example:
#    ./deploy.sh yourdomain.com
#
#  What it does:
#    1. Derives all service URLs from the domain you provide
#    2. Generates a secure INSTANCE_SECRET if one is not already in .env
#    3. Writes (or updates) .env
#    4. Runs: docker compose up -d --build
#
#  Prerequisites:
#    - Docker >= 24 with Compose v2
#    - DNS A records for all five subdomains pointing at this server:
#        app.<domain>
#        docs.<domain>
#        convex.<domain>
#        convex-site.<domain>
#        convex-dashboard.<domain>
# =============================================================================

set -euo pipefail

DOMAIN="${1:-}"
VITE_WORKOS_CLIENT_ID="${2:-}"
VITE_WORKOS_REDIRECT_URI="${3:-}"

if [[ -z "$DOMAIN" ]]; then
  echo "Usage: $0 <domain> [workos_client_id] [workos_redirect_uri]"
  echo "  e.g. $0 yourdomain.com client_XXXXXXXXXXXXXXXXXXXXXXXXXXXX https://app.yourdomain.com/callback"
  exit 1
fi

ENV_FILE=".env"

# ── Generate or preserve INSTANCE_SECRET ──────────────────────────────────────
# If .env already contains a non-empty INSTANCE_SECRET, keep it so existing
# Convex data remains accessible after re-deploys.
EXISTING_SECRET=""
if [[ -f "$ENV_FILE" ]]; then
  EXISTING_SECRET=$(grep -E '^INSTANCE_SECRET=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
fi

if [[ -n "$EXISTING_SECRET" ]]; then
  INSTANCE_SECRET="$EXISTING_SECRET"
  echo "ℹ️  Reusing existing INSTANCE_SECRET from $ENV_FILE"
else
  INSTANCE_SECRET=$(openssl rand -hex 32)
  echo "✅ Generated new INSTANCE_SECRET"
fi

EXISTING_WORKOS_CLIENT_ID=""
EXISTING_WORKOS_REDIRECT_URI=""

if [[ -f "$ENV_FILE" ]]; then
  EXISTING_WORKOS_CLIENT_ID=$(grep -E '^VITE_WORKOS_CLIENT_ID=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
  EXISTING_WORKOS_REDIRECT_URI=$(grep -E '^VITE_WORKOS_REDIRECT_URI=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '"' || true)
fi

if [[ -n "$EXISTING_WORKOS_CLIENT_ID" ]]; then
  VITE_WORKOS_CLIENT_ID="$EXISTING_WORKOS_CLIENT_ID"
  echo "ℹ️  Reusing existing VITE_WORKOS_CLIENT_ID from $ENV_FILE"
fi

if [[ -n "$EXISTING_WORKOS_REDIRECT_URI" ]]; then
  VITE_WORKOS_REDIRECT_URI="$EXISTING_WORKOS_REDIRECT_URI"
  echo "ℹ️  Reusing existing VITE_WORKOS_REDIRECT_URI from $ENV_FILE"
fi

if [[ -z "$VITE_WORKOS_CLIENT_ID" ]]; then
  echo "⚠️  VITE_WORKOS_CLIENT_ID is not set. SSO login via WorkOS will be disabled."
else
  echo "✅ Using VITE_WORKOS_CLIENT_ID: $VITE_WORKOS_CLIENT_ID"
fi

if [[ -z "$VITE_WORKOS_REDIRECT_URI" ]]; then
  echo "⚠️  VITE_WORKOS_REDIRECT_URI is not set. SSO login via WorkOS will be disabled."
else
  echo "✅ Using VITE_WORKOS_REDIRECT_URI: $VITE_WORKOS_REDIRECT_URI"
fi

# ── Write .env ─────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — do not commit this file
DOMAIN=$DOMAIN

INSTANCE_NAME=3reco-production
INSTANCE_SECRET=$INSTANCE_SECRET

CONVEX_CLOUD_ORIGIN=https://convex.$DOMAIN
CONVEX_SITE_ORIGIN=https://convex-site.$DOMAIN

VITE_CONVEX_URL=https://convex.$DOMAIN
VITE_CONVEX_AUTH_DOMAIN=https://convex-site.$DOMAIN

VITE_WORKOS_CLIENT_ID=$VITE_WORKOS_CLIENT_ID
VITE_WORKOS_REDIRECT_URI=$VITE_WORKOS_REDIRECT_URI
EOF

echo "✅ Written $ENV_FILE for domain: $DOMAIN"

# ── Deploy ─────────────────────────────────────────────────────────────────────
echo ""
echo "🚀 Starting stack..."
docker compose up -d --build

echo ""
echo "✅ Stack is up. Services:"
echo "   https://app.$DOMAIN"
echo "   https://docs.$DOMAIN"
echo "   https://convex.$DOMAIN"
echo "   https://convex-site.$DOMAIN"
echo "   https://convex-dashboard.$DOMAIN"
echo ""
echo "⚠️  First deploy? Generate the Convex admin key:"
echo "   docker compose exec convex-backend ./generate_admin_key.sh"
echo ""
echo "   Then deploy Convex functions:"
echo "   cd 3reco && CONVEX_SELF_HOSTED_URL=https://convex.$DOMAIN \\"
echo "     CONVEX_SELF_HOSTED_ADMIN_KEY=<key> bunx convex deploy"
