/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StockRouteImport } from './routes/stock'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MarketIndexRouteImport } from './routes/market/index'
import { Route as MarketOutgoingRouteImport } from './routes/market/outgoing'
import { Route as MarketIncomingRouteImport } from './routes/market/incoming'
import { Route as MarketRequestIdRouteImport } from './routes/market/$requestId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as MarketStoreSellerIdRouteImport } from './routes/market/store.$sellerId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketOutgoingRoute = MarketOutgoingRouteImport.update({
  id: '/market/outgoing',
  path: '/market/outgoing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIncomingRoute = MarketIncomingRouteImport.update({
  id: '/market/incoming',
  path: '/market/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRequestIdRoute = MarketRequestIdRouteImport.update({
  id: '/market/$requestId',
  path: '/market/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketStoreSellerIdRoute = MarketStoreSellerIdRouteImport.update({
  id: '/market/store/$sellerId',
  path: '/market/store/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/materials': typeof MaterialsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/market/$requestId': typeof MarketRequestIdRoute
  '/market/incoming': typeof MarketIncomingRoute
  '/market/outgoing': typeof MarketOutgoingRoute
  '/market/': typeof MarketIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/market/store/$sellerId': typeof MarketStoreSellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/materials': typeof MaterialsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/market/$requestId': typeof MarketRequestIdRoute
  '/market/incoming': typeof MarketIncomingRoute
  '/market/outgoing': typeof MarketOutgoingRoute
  '/market': typeof MarketIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/market/store/$sellerId': typeof MarketStoreSellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/materials': typeof MaterialsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/market/$requestId': typeof MarketRequestIdRoute
  '/market/incoming': typeof MarketIncomingRoute
  '/market/outgoing': typeof MarketOutgoingRoute
  '/market/': typeof MarketIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/market/store/$sellerId': typeof MarketStoreSellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/materials'
    | '/stock'
    | '/transactions'
    | '/admin/users'
    | '/market/$requestId'
    | '/market/incoming'
    | '/market/outgoing'
    | '/market/'
    | '/profile/'
    | '/market/store/$sellerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/materials'
    | '/stock'
    | '/transactions'
    | '/admin/users'
    | '/market/$requestId'
    | '/market/incoming'
    | '/market/outgoing'
    | '/market'
    | '/profile'
    | '/market/store/$sellerId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/materials'
    | '/stock'
    | '/transactions'
    | '/admin/users'
    | '/market/$requestId'
    | '/market/incoming'
    | '/market/outgoing'
    | '/market/'
    | '/profile/'
    | '/market/store/$sellerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRoute
  MaterialsRoute: typeof MaterialsRoute
  StockRoute: typeof StockRoute
  TransactionsRoute: typeof TransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MarketRequestIdRoute: typeof MarketRequestIdRoute
  MarketIncomingRoute: typeof MarketIncomingRoute
  MarketOutgoingRoute: typeof MarketOutgoingRoute
  MarketIndexRoute: typeof MarketIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  MarketStoreSellerIdRoute: typeof MarketStoreSellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/outgoing': {
      id: '/market/outgoing'
      path: '/market/outgoing'
      fullPath: '/market/outgoing'
      preLoaderRoute: typeof MarketOutgoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/incoming': {
      id: '/market/incoming'
      path: '/market/incoming'
      fullPath: '/market/incoming'
      preLoaderRoute: typeof MarketIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$requestId': {
      id: '/market/$requestId'
      path: '/market/$requestId'
      fullPath: '/market/$requestId'
      preLoaderRoute: typeof MarketRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/store/$sellerId': {
      id: '/market/store/$sellerId'
      path: '/market/store/$sellerId'
      fullPath: '/market/store/$sellerId'
      preLoaderRoute: typeof MarketStoreSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRoute,
  MaterialsRoute: MaterialsRoute,
  StockRoute: StockRoute,
  TransactionsRoute: TransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  MarketRequestIdRoute: MarketRequestIdRoute,
  MarketIncomingRoute: MarketIncomingRoute,
  MarketOutgoingRoute: MarketOutgoingRoute,
  MarketIndexRoute: MarketIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  MarketStoreSellerIdRoute: MarketStoreSellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
