/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as CollectorsRouteImport } from './routes/collectors'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MarketIndexRouteImport } from './routes/market/index'
import { Route as TransactionsSalesRouteImport } from './routes/transactions/sales'
import { Route as TransactionsPurchasesRouteImport } from './routes/transactions/purchases'
import { Route as MarketOutgoingRouteImport } from './routes/market/outgoing'
import { Route as MarketIncomingRouteImport } from './routes/market/incoming'
import { Route as MarketRequestIdRouteImport } from './routes/market/$requestId'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as MarketStoreSellerIdRouteImport } from './routes/market/store.$sellerId'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorsRoute = CollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsSalesRoute = TransactionsSalesRouteImport.update({
  id: '/transactions/sales',
  path: '/transactions/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsPurchasesRoute = TransactionsPurchasesRouteImport.update({
  id: '/transactions/purchases',
  path: '/transactions/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketOutgoingRoute = MarketOutgoingRouteImport.update({
  id: '/market/outgoing',
  path: '/market/outgoing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIncomingRoute = MarketIncomingRouteImport.update({
  id: '/market/incoming',
  path: '/market/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRequestIdRoute = MarketRequestIdRouteImport.update({
  id: '/market/$requestId',
  path: '/market/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketStoreSellerIdRoute = MarketStoreSellerIdRouteImport.update({
  id: '/market/store/$sellerId',
  path: '/market/store/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/collectors': typeof CollectorsRoute
  '/materials': typeof MaterialsRoute
  '/stock': typeof StockRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/market/$requestId': typeof MarketRequestIdRoute
  '/market/incoming': typeof MarketIncomingRoute
  '/market/outgoing': typeof MarketOutgoingRoute
  '/transactions/purchases': typeof TransactionsPurchasesRoute
  '/transactions/sales': typeof TransactionsSalesRoute
  '/market/': typeof MarketIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/market/store/$sellerId': typeof MarketStoreSellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/collectors': typeof CollectorsRoute
  '/materials': typeof MaterialsRoute
  '/stock': typeof StockRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/market/$requestId': typeof MarketRequestIdRoute
  '/market/incoming': typeof MarketIncomingRoute
  '/market/outgoing': typeof MarketOutgoingRoute
  '/transactions/purchases': typeof TransactionsPurchasesRoute
  '/transactions/sales': typeof TransactionsSalesRoute
  '/market': typeof MarketIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/market/store/$sellerId': typeof MarketStoreSellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/collectors': typeof CollectorsRoute
  '/materials': typeof MaterialsRoute
  '/stock': typeof StockRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/market/$requestId': typeof MarketRequestIdRoute
  '/market/incoming': typeof MarketIncomingRoute
  '/market/outgoing': typeof MarketOutgoingRoute
  '/transactions/purchases': typeof TransactionsPurchasesRoute
  '/transactions/sales': typeof TransactionsSalesRoute
  '/market/': typeof MarketIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/market/store/$sellerId': typeof MarketStoreSellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/collectors'
    | '/materials'
    | '/stock'
    | '/admin/users'
    | '/auth/reset-password'
    | '/market/$requestId'
    | '/market/incoming'
    | '/market/outgoing'
    | '/transactions/purchases'
    | '/transactions/sales'
    | '/market/'
    | '/profile/'
    | '/transactions/'
    | '/market/store/$sellerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/collectors'
    | '/materials'
    | '/stock'
    | '/admin/users'
    | '/auth/reset-password'
    | '/market/$requestId'
    | '/market/incoming'
    | '/market/outgoing'
    | '/transactions/purchases'
    | '/transactions/sales'
    | '/market'
    | '/profile'
    | '/transactions'
    | '/market/store/$sellerId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/collectors'
    | '/materials'
    | '/stock'
    | '/admin/users'
    | '/auth/reset-password'
    | '/market/$requestId'
    | '/market/incoming'
    | '/market/outgoing'
    | '/transactions/purchases'
    | '/transactions/sales'
    | '/market/'
    | '/profile/'
    | '/transactions/'
    | '/market/store/$sellerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRoute
  CollectorsRoute: typeof CollectorsRoute
  MaterialsRoute: typeof MaterialsRoute
  StockRoute: typeof StockRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  MarketRequestIdRoute: typeof MarketRequestIdRoute
  MarketIncomingRoute: typeof MarketIncomingRoute
  MarketOutgoingRoute: typeof MarketOutgoingRoute
  TransactionsPurchasesRoute: typeof TransactionsPurchasesRoute
  TransactionsSalesRoute: typeof TransactionsSalesRoute
  MarketIndexRoute: typeof MarketIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  MarketStoreSellerIdRoute: typeof MarketStoreSellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectors': {
      id: '/collectors'
      path: '/collectors'
      fullPath: '/collectors'
      preLoaderRoute: typeof CollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/sales': {
      id: '/transactions/sales'
      path: '/transactions/sales'
      fullPath: '/transactions/sales'
      preLoaderRoute: typeof TransactionsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/purchases': {
      id: '/transactions/purchases'
      path: '/transactions/purchases'
      fullPath: '/transactions/purchases'
      preLoaderRoute: typeof TransactionsPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/outgoing': {
      id: '/market/outgoing'
      path: '/market/outgoing'
      fullPath: '/market/outgoing'
      preLoaderRoute: typeof MarketOutgoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/incoming': {
      id: '/market/incoming'
      path: '/market/incoming'
      fullPath: '/market/incoming'
      preLoaderRoute: typeof MarketIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$requestId': {
      id: '/market/$requestId'
      path: '/market/$requestId'
      fullPath: '/market/$requestId'
      preLoaderRoute: typeof MarketRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/store/$sellerId': {
      id: '/market/store/$sellerId'
      path: '/market/store/$sellerId'
      fullPath: '/market/store/$sellerId'
      preLoaderRoute: typeof MarketStoreSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRoute,
  CollectorsRoute: CollectorsRoute,
  MaterialsRoute: MaterialsRoute,
  StockRoute: StockRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  MarketRequestIdRoute: MarketRequestIdRoute,
  MarketIncomingRoute: MarketIncomingRoute,
  MarketOutgoingRoute: MarketOutgoingRoute,
  TransactionsPurchasesRoute: TransactionsPurchasesRoute,
  TransactionsSalesRoute: TransactionsSalesRoute,
  MarketIndexRoute: MarketIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  MarketStoreSellerIdRoute: MarketStoreSellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
